schemaVersion: 2.2.2
metadata:
  name: test-devfile-v1
components:
  - name: tools
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.12
      memoryLimit: 12Gi
      memoryRequest: 4Gi
      cpuLimit: '6'
      cpuRequest: '2'
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
      volumeMounts:
        - name: jetbrains-config
          path: /home/user/.config/JetBrains
  - name: jetbrains-config
    volume:
      size: 10G
#commands:
#  - id: build
#    exec:
#      component: tools
#      workingDir: ${PROJECTS_ROOT}/lombok-project-sample
#      commandLine: mvn clean install
#      group:
#        kind: build
#        isDefault: true