schemaVersion: 2.2.2
metadata:
  name: test-devfile-v1
components:
  - name: tools
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.12
      memoryLimit: 6Gi
      memoryRequest: 2Gi
      cpuLimit: '4'
      cpuRequest: '1'
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
      volumeMounts:
        - name: gradle
          path: /home/user/.gradle
  - name: gradle
    volume:
      size: 16G
#commands:
#  - id: build
#    exec:
#      component: tools
#      workingDir: ${PROJECTS_ROOT}/lombok-project-sample
#      commandLine: mvn clean install
#      group:
#        kind: build
#        isDefault: true